baseurl = "https://dwgoblue.github.io/"
languageCode = "en-us"
title = "DW Blog"
theme = "casper"
paginate = 2
Copyright = "© All rights reserved - 2020"
canonifyurls = true

[params]
description = "A scientist who loves to challenge himself."
authorlocation = "Ann Arbor, MI, USA"
cover = "images/cover.jpg"
author = "Da-Wei Lin"
bio= "Bioinformatics PhD student|University of Michigan, Ann Arbor"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/signature.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
githubName = "dwgoblue"
twitterName = "DaWeiLin4"
linkedinName = "da-wei-lin-331006197"
email = "daweilin@umich.edu"
instagramName = "your ins name"
hideHUGOSupport = false
[[menu.main]]  # here are the buttons on the menu
  name = "Home" # Button will display as "Home"
  weight = 100 # the weight decides the position of the button (higher or lower)
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
  url = "/post"
  weight = 40

[[menu.main]]
  name = "About me"
  weight = -100
  identifier = "about"
  url = "/about"

#[[menu.main]]
#  name = "Contact"
#  weight = -110
#  identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
#  url = "/contact"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"